### PR TITLE
openssl (dtls) messages are not processed #147

### PR DESCRIPTION
**Pull request by vincent-iQontrol**
- fixed missing namespace
- moved DtlsClientConnection before binding to fix listen issues

### CODE REVIEW

**Review by JKRhb — APPROVED** [review]
@shamblett Could you have a look on this PR and #146? They should be mergeable right away :)

**Comment by shamblett** [comment]
OK done, do you want a release for this? If so I'll do this tomorrow.

**Comment by JKRhb** [comment]
I think a new release would be nice :) However, I guess it would be another major one due to some API changes, right?

**Comment by shamblett** [comment]
Yep we need a new one, 4 other PR's have gone into this also, version 7.0.0 published, a COAP package for xmas!

**Pull request merged**
