### PR TITLE
Fix every first request failure

### PR DESCRIPTION
**Pull request by a1573595**
Hi, thank your sample, I found some bug and try to fix it, hop it can help.

1. Socket binding is asynchronous, you should use await to ensure that the initialization is completed before the request.
2. Use CoapNetworkUDP  to avoid generation CoapNetworkUDP  again.

#28

### CODE REVIEW

**Comment by a1573595** [comment]
#28

**Comment by a1573595** [comment]
Sorry for that, I am working on windows, some path setting is different.

**Comment by shamblett** [comment]
Thanks for this, its much better, merged on PR #31

**Comment by a1573595** [comment]
If you think I modified something that shouldn't be changed, you can tell me directly. I will close it and submit new pull.
Don't erase my contribution, I won’t help anymore.

**Comment by shamblett** [comment]
No you didnt do anything wrong, when I changed the merge base to my issue28 branch I reviewed the code which was ok but forgot to merge it, s when I merged the branch your code wasn't in it so I creted a nee branch, manually added yor changes and merged it.

This was my fault not yours. Thanks again.

**Pull request merged**
