### PR TITLE
refactor: replace OSCORE Interfaces with Mixins

### PR DESCRIPTION
**Pull request by JKRhb**
This PR proposes a trivial refactoring, turning the interfaces for identifying OSCORE class into more idiomatic Mixins.

### CODE REVIEW

**Comment by JKRhb** [comment]
@shamblett I think this PR as well as #162, #163, #164, #165, and #167 are rather trivial and could be merged right away.

With #160, I made a lot of progress, there are some minor aspects that still need fixing. There might also be some discussion required if this is the general direction we should go for. However, I think being able to have only client for requests to multiple endpoints should be handy, especially once we also start to support TCP and WebSockets. Being able to use only one socket for multiple peers should also increase the efficiency of the implementation if you have a lot of devices you want to communicate with.

**Comment by shamblett** [comment]
All done except for #167 which has a conflict, also there have been 11 PR merges since 7.0.0 so I'm thinking we should have another major release at this point.

**Comment by JKRhb** [comment]
> All done except for #167 which has a conflict, also there have been 11 PR merges since 7.0.0 so I'm thinking we should have another major release at this point.

Awesome, thank you! :) #167 should now be ready as well. A new major release sounds very good! For 9.0.0 we can then concentrate on the discussion of new major features (TCP, WebSockets, maybe even OSCORE).

**Comment by shamblett** [comment]
All done, version 8.0.0 published.

**Pull request merged**
